title: Jingliuwu
author: Kurulucifer
email: bobbtenders@gmail.com
description: >-
  I love Jingliuwu.

social:
  twitter: Atdan86
  facebook: barackobama
  instagram: zy0xbtw
  github: kurulucifer
  linkedin: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
