title: Multiverse by HTML5 UP
author: Kurulucifer
email: kurulucifer.elysione@gmail.com
description: >-
  I love Jingliuwu.

social:
  twitter: Atdan86
  facebook: barackobama
  instagram: warriorsaucey_
  github: kurulucifer
  linkedin: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
